vich_uploader:
    db_driver: orm

    mappings:
        livre_images:
           uri_prefix: 'uploads/illustrations'
           upload_destination: "%kernel.project_dir%/public/uploads/illustrations"
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true
